# Generated by Django 5.1.2 on 2024-12-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5),
        ),
    ]
