# Generated by Django 5.1.2 on 2024-12-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_remove_producto_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='img',
        ),
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/images/productos/'),
        ),
    ]
