# Generated by Django 5.1.2 on 2024-12-08 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0003_alter_pedido_options_remove_pedido_fecha_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_pedido',
            name='iva',
        ),
    ]
