# Generated by Django 5.1.2 on 2024-12-02 16:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe contener entre 7 y 8 números seguidos de un dígito verificador (0-9 o K).', regex='^\\d{7,8}[0-9Kk]$')])),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener 9 dígitos', regex='^\\d{9}$')])),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator(message='Formato de email inválido')])),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='InteraccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('tipo_interaccion', models.CharField(choices=[('Llamada', 'Llamada'), ('Email', 'Email'), ('Reunión', 'Reunión'), ('Otro', 'Otro')], max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
            ],
            options={
                'verbose_name': 'Interacción del Cliente',
                'verbose_name_plural': 'Interacciones de Clientes',
                'db_table': 'interaccion_cliente',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['rut', 'email'], name='cliente_rut_6f467c_idx'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('rut', 'email'), name='unique_rut_email'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('rut', 'email')},
        ),
        migrations.AddIndex(
            model_name='interaccioncliente',
            index=models.Index(fields=['cliente', 'fecha'], name='interaccion_cliente_823e81_idx'),
        ),
        migrations.AddConstraint(
            model_name='interaccioncliente',
            constraint=models.UniqueConstraint(fields=('cliente', 'fecha'), name='unique_cliente_fecha'),
        ),
        migrations.AlterUniqueTogether(
            name='interaccioncliente',
            unique_together={('cliente', 'fecha')},
        ),
    ]
