# Generated by Django 5.1.2 on 2024-12-02 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('codigo_region', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('codigo_provincia', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='Ubicacion.region')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('codigo_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(db_column='provincia_id', on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='Ubicacion.provincia')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'comuna',
                'indexes': [models.Index(fields=['codigo_comuna'], name='comuna_codigo__635334_idx')],
            },
        ),
    ]
